'use client'

import { useState } from 'react'
import { useQuery } from '@/lib/query'
import { apiClient } from '@/lib/api'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { MessageSquare, Calendar, ChevronDown, ChevronUp } from '@/components/icons'
import { FeedbackButton } from '@/components/query/FeedbackButton'

export default function HistoryPage() {
  const [expandedQuery, setExpandedQuery] = useState<string | null>(null)

  const { data: queries, isLoading } = useQuery({
    queryKey: ['queries'],
    queryFn: async () => {
      const response = await apiClient.getQueries(50, 0)
      return response.data
    },
  })

  const toggleQuery = (queryId: string) => {
    setExpandedQuery(expandedQuery === queryId ? null : queryId)
  }

  if (isLoading) {
    return (
      <div className="text-center py-12">
        <div className="w-8 h-8 border-4 border-jio-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
        <p className="text-gray-600">Loading history...</p>
      </div>
    )
  }

  if (!queries || queries.length === 0) {
    return (
      <div className="space-y-6">
        <h1 className="text-3xl font-bold text-gray-900">Query History</h1>
        <Card>
          <CardContent className="text-center py-12">
            <MessageSquare className="w-12 h-12 text-gray-400 mx-auto mb-4" />
            <h3 className="text-lg font-semibold mb-2">No Questions Yet</h3>
            <p className="text-gray-600 mb-6">
              Your astrological query history will appear here
            </p>
            <Button onClick={() => window.location.href = '/dashboard/ask'}>
              Ask Your First Question
            </Button>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-gray-900">Query History</h1>
        <p className="text-gray-600 mt-2">
          View your past questions and AI-powered insights
        </p>
      </div>

      <div className="space-y-4">
        {queries.map((item: any) => {
          const query = item?.query ?? item
          if (!query) {
            return null
          }

          const queryId = query.id ?? item?.id
          const responses = item?.responses ?? query.responses ?? (item?.response ? [item.response] : [])
          const isExpanded = expandedQuery === queryId
          const response = responses?.[0] // Get first response from responses array

          return (
            <Card key={queryId ?? query.question} className="overflow-hidden">
              <button
                onClick={() => queryId && toggleQuery(queryId)}
                className="w-full text-left"
              >
                <CardHeader className="hover:bg-gray-50 transition-colors cursor-pointer">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <CardTitle className="text-lg line-clamp-2">{query.question ?? 'Question unavailable'}</CardTitle>
                      <CardDescription className="flex items-center gap-3 mt-2">
                        <span className="flex items-center gap-1">
                          <Calendar className="w-3 h-3" />
                          {query.created_at ? new Date(query.created_at).toLocaleDateString() : 'Unknown date'}
                        </span>
                        {query.category && (
                          <span className="text-xs bg-jio-100 text-jio-700 px-2 py-1 rounded">
                            {query.category}
                          </span>
                        )}
                      </CardDescription>
                    </div>
                    <div>
                      {isExpanded ? (
                        <ChevronUp className="w-5 h-5 text-gray-400" />
                      ) : (
                        <ChevronDown className="w-5 h-5 text-gray-400" />
                      )}
                    </div>
                  </div>
                </CardHeader>
              </button>

              {isExpanded && response && (
                <CardContent className="border-t bg-gray-50">
                  <div className="prose prose-sm max-w-none py-4">
                    <div className="whitespace-pre-wrap text-gray-800">
                      {response.interpretation}
                    </div>
                  </div>

                  <div className="flex items-center justify-between pt-4 border-t">
                    <div className="text-xs text-gray-500">
                      Generated by {response.ai_model} • {response.tokens_used} tokens
                    </div>
                    <FeedbackButton responseId={response.id} />
                  </div>
                </CardContent>
              )}
            </Card>
          )
        })}
      </div>
    </div>
  )
}
