-- Populate Tarot Cards Table
-- All 78 cards of the traditional Rider-Waite tarot deck
-- 22 Major Arcana + 56 Minor Arcana (14 cards × 4 suits)

-- ==================================================
-- MAJOR ARCANA (0-21) - 22 cards
-- ==================================================

INSERT INTO tarot_cards (card_number, name, suit, arcana_type, upright_meaning, reversed_meaning, upright_keywords, reversed_keywords, imagery_description, element, astrological_association, numerological_value) VALUES
(0, 'The Fool', 'major_arcana', 'major',
 'New beginnings, spontaneity, innocence, free spirit, adventure, unlimited potential',
 'Recklessness, fear of unknown, poor judgment, lack of direction, naivety',
 '["new beginnings", "spontaneity", "innocence", "freedom", "adventure"]'::jsonb,
 '["recklessness", "fear", "poor judgment", "foolishness", "chaos"]'::jsonb,
 'A young person stands at the edge of a cliff, about to step into the unknown, carrying only a small bag',
 'air', 'Uranus', 0),

(1, 'The Magician', 'major_arcana', 'major',
 'Manifestation, resourcefulness, power, inspired action, skill, willpower',
 'Manipulation, poor planning, untapped talents, illusion, trickery',
 '["manifestation", "power", "skill", "action", "resourcefulness"]'::jsonb,
 '["manipulation", "illusion", "unused potential", "deception"]'::jsonb,
 'A figure stands before a table with the four suits, one hand pointing to heaven, one to earth',
 'air', 'Mercury', 1),

(2, 'The High Priestess', 'major_arcana', 'major',
 'Intuition, sacred knowledge, divine feminine, subconscious mind, mystery',
 'Secrets, disconnected from intuition, withdrawal, silence, hidden motives',
 '["intuition", "mystery", "wisdom", "divine feminine", "inner voice"]'::jsonb,
 '["hidden agenda", "lack of intuition", "withdrawal", "secrets"]'::jsonb,
 'A woman sits between two pillars, holding a scroll, with the moon at her feet',
 'water', 'Moon', 2),

(3, 'The Empress', 'major_arcana', 'major',
 'Femininity, beauty, nature, nurturing, abundance, fertility, creativity',
 'Creative block, dependence on others, emptiness, neglect, smothering',
 '["abundance", "nurturing", "fertility", "beauty", "nature"]'::jsonb,
 '["creative block", "dependence", "neglect", "emptiness"]'::jsonb,
 'A pregnant woman sits on a throne in a lush garden surrounded by wheat and flowing water',
 'earth', 'Venus', 3),

(4, 'The Emperor', 'major_arcana', 'major',
 'Authority, establishment, structure, father figure, leadership, control',
 'Domination, excessive control, lack of discipline, inflexibility, tyranny',
 '["authority", "structure", "leadership", "control", "stability"]'::jsonb,
 '["domination", "rigidity", "tyranny", "inflexibility"]'::jsonb,
 'A powerful ruler sits on a throne decorated with rams heads, holding a scepter',
 'fire', 'Aries', 4),

(5, 'The Hierophant', 'major_arcana', 'major',
 'Spiritual wisdom, religious beliefs, conformity, tradition, institutions, group identification',
 'Personal beliefs, freedom, challenging the status quo, rebellion',
 '["tradition", "conformity", "institutions", "spiritual wisdom", "teaching"]'::jsonb,
 '["rebellion", "unconventionality", "personal beliefs", "freedom"]'::jsonb,
 'A religious figure sits between two pillars, blessing two acolytes',
 'earth', 'Taurus', 5),

(6, 'The Lovers', 'major_arcana', 'major',
 'Love, harmony, relationships, values alignment, choices, union, partnerships',
 'Self-love, disharmony, imbalance, misalignment of values, conflict',
 '["love", "relationships", "harmony", "choices", "union"]'::jsonb,
 '["disharmony", "conflict", "poor choices", "imbalance"]'::jsonb,
 'A man and woman stand beneath an angel, representing choice and divine union',
 'air', 'Gemini', 6),

(7, 'The Chariot', 'major_arcana', 'major',
 'Control, willpower, success, action, determination, victory, ambition',
 'Self-discipline, opposition, lack of direction, scattered energy',
 '["victory", "willpower", "determination", "success", "control"]'::jsonb,
 '["lack of direction", "opposition", "self-discipline needed"]'::jsonb,
 'A warrior rides a chariot pulled by two sphinxes, one black and one white',
 'water', 'Cancer', 7),

(8, 'Strength', 'major_arcana', 'major',
 'Strength, courage, patience, control, compassion, inner power, gentle influence',
 'Inner weakness, self-doubt, low energy, raw emotion, lack of confidence',
 '["inner strength", "courage", "patience", "compassion", "control"]'::jsonb,
 '["weakness", "self-doubt", "lack of confidence", "raw emotion"]'::jsonb,
 'A woman gently closes the jaws of a lion, showing strength through compassion',
 'fire', 'Leo', 8),

(9, 'The Hermit', 'major_arcana', 'major',
 'Soul searching, introspection, inner guidance, solitude, spiritual enlightenment',
 'Isolation, loneliness, withdrawal, lost your way, reclusive',
 '["introspection", "solitude", "inner guidance", "wisdom", "enlightenment"]'::jsonb,
 '["isolation", "loneliness", "withdrawal", "lost"]'::jsonb,
 'An old man stands alone on a mountain peak, holding a lantern to light the way',
 'earth', 'Virgo', 9),

(10, 'Wheel of Fortune', 'major_arcana', 'major',
 'Good luck, karma, life cycles, destiny, turning point, change of fortune',
 'Bad luck, resistance to change, breaking cycles, lack of control',
 '["destiny", "cycles", "turning point", "good fortune", "karma"]'::jsonb,
 '["bad luck", "resistance", "breaking cycles", "lack of control"]'::jsonb,
 'A wheel turns in the sky, with figures rising and falling with its rotation',
 'fire', 'Jupiter', 10),

(11, 'Justice', 'major_arcana', 'major',
 'Justice, fairness, truth, cause and effect, law, accountability, integrity',
 'Unfairness, lack of accountability, dishonesty, legal complications',
 '["justice", "fairness", "truth", "law", "accountability"]'::jsonb,
 '["unfairness", "dishonesty", "avoiding responsibility", "bias"]'::jsonb,
 'A figure sits on a throne holding scales and a sword, representing balanced judgment',
 'air', 'Libra', 11),

(12, 'The Hanged Man', 'major_arcana', 'major',
 'Suspension, restriction, letting go, sacrifice, new perspective, contemplation',
 'Delays, resistance, stalling, indecision, martyrdom',
 '["surrender", "new perspective", "contemplation", "sacrifice", "letting go"]'::jsonb,
 '["delays", "resistance", "stalling", "indecision"]'::jsonb,
 'A man hangs upside down from a tree, appearing serene and enlightened',
 'water', 'Neptune', 12),

(13, 'Death', 'major_arcana', 'major',
 'Endings, change, transformation, transition, letting go, new beginnings',
 'Resistance to change, personal transformation, inner purging, fear of change',
 '["transformation", "endings", "change", "transition", "new beginnings"]'::jsonb,
 '["resistance to change", "stagnation", "fear", "inability to let go"]'::jsonb,
 'A skeleton in armor rides a white horse, symbolizing the transformative power of endings',
 'water', 'Scorpio', 13),

(14, 'Temperance', 'major_arcana', 'major',
 'Balance, moderation, patience, purpose, meaning, flow, harmony',
 'Imbalance, excess, self-healing, realignment, lack of long-term vision',
 '["balance", "moderation", "patience", "harmony", "purpose"]'::jsonb,
 '["imbalance", "excess", "lack of vision", "misalignment"]'::jsonb,
 'An angel pours water between two cups, representing the balance of opposing forces',
 'fire', 'Sagittarius', 14),

(15, 'The Devil', 'major_arcana', 'major',
 'Shadow self, attachment, addiction, restriction, sexuality, materialism',
 'Releasing limiting beliefs, exploring dark thoughts, detachment, freedom',
 '["bondage", "addiction", "materialism", "restriction", "shadow self"]'::jsonb,
 '["freedom", "release", "detachment", "breaking free"]'::jsonb,
 'A horned figure presides over two chained humans, representing bondage to material world',
 'earth', 'Capricorn', 15),

(16, 'The Tower', 'major_arcana', 'major',
 'Sudden change, upheaval, chaos, revelation, awakening, liberation from false beliefs',
 'Personal transformation, fear of change, averting disaster, delayed disaster',
 '["upheaval", "sudden change", "chaos", "revelation", "awakening"]'::jsonb,
 '["fear of change", "averting disaster", "personal transformation"]'::jsonb,
 'A tower struck by lightning with people falling, representing sudden revelation',
 'fire', 'Mars', 16),

(17, 'The Star', 'major_arcana', 'major',
 'Hope, faith, purpose, renewal, spirituality, healing, inspiration',
 'Lack of faith, despair, self-trust, disconnection, pessimism',
 '["hope", "faith", "renewal", "inspiration", "healing"]'::jsonb,
 '["despair", "lack of faith", "disconnection", "pessimism"]'::jsonb,
 'A woman pours water onto land and into a pool beneath the stars, representing hope',
 'air', 'Aquarius', 17),

(18, 'The Moon', 'major_arcana', 'major',
 'Illusion, fear, anxiety, subconscious, intuition, confusion, uncertainty',
 'Release of fear, repressed emotion, inner confusion, clarity slowly coming',
 '["illusion", "intuition", "subconscious", "fear", "mystery"]'::jsonb,
 '["release of fear", "inner turmoil", "confusion", "deception revealed"]'::jsonb,
 'Two dogs howl at the moon while a crayfish emerges from water, representing the subconscious',
 'water', 'Pisces', 18),

(19, 'The Sun', 'major_arcana', 'major',
 'Positivity, fun, warmth, success, vitality, joy, confidence, happiness',
 'Inner child, feeling down, overly optimistic, temporary setback',
 '["joy", "success", "celebration", "positivity", "vitality"]'::jsonb,
 '["sadness", "lack of enthusiasm", "excessive optimism", "inner child"]'::jsonb,
 'A child rides a white horse beneath a bright sun, representing pure joy and success',
 'fire', 'Sun', 19),

(20, 'Judgement', 'major_arcana', 'major',
 'Judgement, rebirth, inner calling, absolution, self-evaluation, reflection',
 'Self-doubt, inner critic, ignoring the call, lack of self-awareness',
 '["judgement", "rebirth", "awakening", "renewal", "calling"]'::jsonb,
 '["self-doubt", "inner critic", "avoiding responsibility"]'::jsonb,
 'An angel sounds a trumpet as people rise from their graves, representing awakening',
 'fire', 'Pluto', 20),

(21, 'The World', 'major_arcana', 'major',
 'Completion, accomplishment, travel, fulfillment, success, achievement, wholeness',
 'Seeking personal closure, short-cut to success, delays, lack of completion',
 '["completion", "accomplishment", "fulfillment", "wholeness", "success"]'::jsonb,
 '["incompletion", "delays", "seeking closure", "short-cuts"]'::jsonb,
 'A figure dances within a wreath, representing completion and wholeness',
 'earth', 'Saturn', 21);

-- ==================================================
-- MINOR ARCANA - WANDS (Fire) - 22-35
-- ==================================================

INSERT INTO tarot_cards (card_number, name, suit, arcana_type, upright_meaning, reversed_meaning, upright_keywords, reversed_keywords, element, numerological_value) VALUES
(22, 'Ace of Wands', 'wands', 'minor',
 'Inspiration, new opportunities, growth, potential, creative spark, breakthrough',
 'Emerging idea, lack of direction, distractions, delays, creative blocks',
 '["inspiration", "new opportunities", "potential", "growth"]'::jsonb,
 '["delays", "distractions", "lack of direction", "creative block"]'::jsonb,
 'fire', 1),

(23, 'Two of Wands', 'wands', 'minor',
 'Future planning, progress, decisions, discovery, personal power, bold moves',
 'Fear of unknown, lack of planning, bad decisions, playing it safe',
 '["planning", "decisions", "progress", "discovery"]'::jsonb,
 '["fear of unknown", "lack of planning", "playing safe"]'::jsonb,
 'fire', 2),

(24, 'Three of Wands', 'wands', 'minor',
 'Expansion, foresight, overseas opportunities, progress, forward planning',
 'Playing it safe, lack of foresight, obstacles, delays, frustration',
 '["expansion", "foresight", "opportunities", "progress"]'::jsonb,
 '["obstacles", "delays", "frustration", "playing safe"]'::jsonb,
 'fire', 3),

(25, 'Four of Wands', 'wands', 'minor',
 'Celebration, joy, harmony, relaxation, homecoming, community, success',
 'Personal celebration, inner harmony, conflict with others, transition',
 '["celebration", "harmony", "homecoming", "community"]'::jsonb,
 '["conflict", "lack of support", "instability"]'::jsonb,
 'fire', 4),

(26, 'Five of Wands', 'wands', 'minor',
 'Conflict, disagreements, competition, tension, diversity, healthy debate',
 'Inner conflict, avoiding conflict, respecting differences, agreement',
 '["conflict", "competition", "tension", "diversity"]'::jsonb,
 '["avoiding conflict", "inner conflict", "agreement"]'::jsonb,
 'fire', 5),

(27, 'Six of Wands', 'wands', 'minor',
 'Success, public recognition, progress, self-confidence, victory, achievement',
 'Private achievement, self-doubt, lack of recognition, punishment, fall from grace',
 '["success", "recognition", "victory", "confidence"]'::jsonb,
 '["self-doubt", "lack of recognition", "ego"]'::jsonb,
 'fire', 6),

(28, 'Seven of Wands', 'wands', 'minor',
 'Challenge, competition, perseverance, protection, standing your ground',
 'Exhaustion, giving up, overwhelmed, defensiveness',
 '["perseverance", "challenge", "standing ground"]'::jsonb,
 '["exhaustion", "giving up", "overwhelmed"]'::jsonb,
 'fire', 7),

(29, 'Eight of Wands', 'wands', 'minor',
 'Movement, fast-paced change, action, alignment, swift communication, travel',
 'Delays, frustration, resisting change, internal alignment',
 '["movement", "speed", "action", "travel"]'::jsonb,
 '["delays", "frustration", "resisting change"]'::jsonb,
 'fire', 8),

(30, 'Nine of Wands', 'wands', 'minor',
 'Resilience, courage, persistence, test of faith, boundaries, last stand',
 'Inner resources, struggle, overwhelm, defensive, paranoia',
 '["resilience", "persistence", "boundaries"]'::jsonb,
 '["exhaustion", "paranoia", "defensive"]'::jsonb,
 'fire', 9),

(31, 'Ten of Wands', 'wands', 'minor',
 'Burden, extra responsibility, hard work, completion, stress, obligation',
 'Doing it all, carrying the burden, delegation, release, breakdown',
 '["burden", "responsibility", "hard work", "stress"]'::jsonb,
 '["delegation", "release", "breakdown"]'::jsonb,
 'fire', 10),

(32, 'Page of Wands', 'wands', 'minor',
 'Inspiration, ideas, discovery, limitless potential, free spirit, good news',
 'Newly-formed ideas, redirecting energy, self-limiting beliefs, procrastination',
 '["inspiration", "discovery", "potential", "enthusiasm"]'::jsonb,
 '["procrastination", "self-limiting", "lack of direction"]'::jsonb,
 'fire', 11),

(33, 'Knight of Wands', 'wands', 'minor',
 'Energy, passion, inspired action, adventure, impulsiveness, fearlessness',
 'Passion project, haste, scattered energy, delays, frustration, recklessness',
 '["passion", "adventure", "action", "energy"]'::jsonb,
 '["recklessness", "haste", "scattered energy"]'::jsonb,
 'fire', 12),

(34, 'Queen of Wands', 'wands', 'minor',
 'Confidence, independence, social butterfly, determination, courage, vibrant',
 'Self-respect, self-confidence, introverted, re-establish sense of self',
 '["confidence", "independence", "vibrant", "determination"]'::jsonb,
 '["self-doubt", "jealousy", "insecurity"]'::jsonb,
 'fire', 13),

(35, 'King of Wands', 'wands', 'minor',
 'Natural leader, vision, entrepreneur, honor, boldness, decisiveness',
 'Impulsiveness, haste, ruthless, high expectations, arrogance',
 '["leadership", "vision", "entrepreneur", "honor"]'::jsonb,
 '["arrogance", "impulsiveness", "ruthlessness"]'::jsonb,
 'fire', 14);

-- ==================================================
-- MINOR ARCANA - CUPS (Water) - 36-49
-- ==================================================

INSERT INTO tarot_cards (card_number, name, suit, arcana_type, upright_meaning, reversed_meaning, upright_keywords, reversed_keywords, element, numerological_value) VALUES
(36, 'Ace of Cups', 'cups', 'minor',
 'Love, new relationships, compassion, creativity, emotional awakening',
 'Self-love, intuition, repressed emotions, blocked creativity',
 '["love", "new relationships", "compassion", "creativity"]'::jsonb,
 '["self-love", "blocked creativity", "repressed emotions"]'::jsonb,
 'water', 1),

(37, 'Two of Cups', 'cups', 'minor',
 'Unified love, partnership, mutual attraction, relationships, harmony, connection',
 'Self-love, break-ups, disharmony, imbalance, distrust',
 '["partnership", "unity", "attraction", "connection"]'::jsonb,
 '["break-up", "imbalance", "distrust"]'::jsonb,
 'water', 2),

(38, 'Three of Cups', 'cups', 'minor',
 'Celebration, friendship, creativity, collaborations, community, group activities',
 'Independence, alone time, hardcore partying, three''s a crowd',
 '["celebration", "friendship", "community", "collaboration"]'::jsonb,
 '["excess", "isolation", "gossip"]'::jsonb,
 'water', 3),

(39, 'Four of Cups', 'cups', 'minor',
 'Meditation, contemplation, apathy, reevaluation, boredom, missed opportunity',
 'Retreat, withdrawal, checking in for alignment, new perspectives',
 '["contemplation", "apathy", "reevaluation"]'::jsonb,
 '["retreat", "withdrawal", "new perspectives"]'::jsonb,
 'water', 4),

(40, 'Five of Cups', 'cups', 'minor',
 'Regret, failure, disappointment, pessimism, grief, loss, mourning',
 'Personal setbacks, self-forgiveness, moving on, acceptance',
 '["regret", "loss", "disappointment", "grief"]'::jsonb,
 '["acceptance", "moving on", "forgiveness"]'::jsonb,
 'water', 5),

(41, 'Six of Cups', 'cups', 'minor',
 'Revisiting the past, childhood memories, innocence, joy, nostalgia, reunion',
 'Living in past, forgiveness, lacking playfulness, moving forward',
 '["nostalgia", "memories", "innocence", "reunion"]'::jsonb,
 '["stuck in past", "naivety", "unrealistic"]'::jsonb,
 'water', 6),

(42, 'Seven of Cups', 'cups', 'minor',
 'Opportunities, choices, wishful thinking, illusion, fantasy, daydreaming',
 'Alignment, personal values, overwhelmed by choices, clarity',
 '["choices", "illusion", "fantasy", "opportunities"]'::jsonb,
 '["clarity", "values", "making choices"]'::jsonb,
 'water', 7),

(43, 'Eight of Cups', 'cups', 'minor',
 'Disappointment, abandonment, withdrawal, escapism, leaving behind, moving on',
 'Trying one more time, indecision, aimless drifting, walking away',
 '["walking away", "withdrawal", "escapism"]'::jsonb,
 '["indecision", "aimless drifting", "fear of moving on"]'::jsonb,
 'water', 8),

(44, 'Nine of Cups', 'cups', 'minor',
 'Contentment, satisfaction, gratitude, wish come true, luxury, pleasure',
 'Inner happiness, materialism, dissatisfaction, indulgence',
 '["contentment", "satisfaction", "wishes", "pleasure"]'::jsonb,
 '["dissatisfaction", "materialism", "indulgence"]'::jsonb,
 'water', 9),

(45, 'Ten of Cups', 'cups', 'minor',
 'Divine love, blissful relationships, harmony, alignment, family happiness',
 'Disconnection, misaligned values, struggling relationships, family conflicts',
 '["happiness", "harmony", "family", "alignment"]'::jsonb,
 '["family conflict", "disconnection", "misalignment"]'::jsonb,
 'water', 10),

(46, 'Page of Cups', 'cups', 'minor',
 'Creative opportunities, intuitive messages, curiosity, possibility, new ideas',
 'New ideas, doubting intuition, creative blocks, emotional immaturity',
 '["creativity", "intuition", "curiosity", "messages"]'::jsonb,
 '["creative blocks", "emotional immaturity"]'::jsonb,
 'water', 11),

(47, 'Knight of Cups', 'cups', 'minor',
 'Creativity, romance, charm, imagination, beauty, following your heart',
 'Overactive imagination, unrealistic, jealousy, moodiness',
 '["romance", "charm", "imagination", "following heart"]'::jsonb,
 '["unrealistic", "jealousy", "moodiness"]'::jsonb,
 'water', 12),

(48, 'Queen of Cups', 'cups', 'minor',
 'Compassionate, caring, emotionally stable, intuitive, in flow, nurturing',
 'Inner feelings, self-care, self-love, co-dependency, giving too much',
 '["compassion", "intuition", "nurturing", "emotional stability"]'::jsonb,
 '["co-dependency", "martyrdom", "insecurity"]'::jsonb,
 'water', 13),

(49, 'King of Cups', 'cups', 'minor',
 'Emotionally balanced, compassionate, diplomatic, calm, wisdom, tolerance',
 'Self-compassion, inner feelings, moodiness, emotional manipulation',
 '["emotional balance", "compassion", "diplomacy", "wisdom"]'::jsonb,
 '["emotional manipulation", "moodiness", "volatility"]'::jsonb,
 'water', 14);

-- ==================================================
-- MINOR ARCANA - SWORDS (Air) - 50-63
-- ==================================================

INSERT INTO tarot_cards (card_number, name, suit, arcana_type, upright_meaning, reversed_meaning, upright_keywords, reversed_keywords, element, numerological_value) VALUES
(50, 'Ace of Swords', 'swords', 'minor',
 'Breakthrough, clarity, sharp mind, new ideas, mental clarity, truth, justice',
 'Inner clarity, re-thinking an idea, clouded judgment, confusion',
 '["clarity", "breakthrough", "truth", "mental power"]'::jsonb,
 '["confusion", "chaos", "lack of clarity"]'::jsonb,
 'air', 1),

(51, 'Two of Swords', 'swords', 'minor',
 'Difficult decisions, weighing options, impasse, avoidance, stalemate',
 'Indecision, confusion, information overload, no right choice',
 '["difficult choice", "stalemate", "avoidance"]'::jsonb,
 '["indecision", "confusion", "information overload"]'::jsonb,
 'air', 2),

(52, 'Three of Swords', 'swords', 'minor',
 'Heartbreak, emotional pain, sorrow, grief, hurt, rejection, sadness',
 'Negative self-talk, releasing pain, optimism, forgiveness, healing',
 '["heartbreak", "sorrow", "pain", "grief"]'::jsonb,
 '["healing", "forgiveness", "recovery"]'::jsonb,
 'air', 3),

(53, 'Four of Swords', 'swords', 'minor',
 'Rest, relaxation, meditation, contemplation, recuperation, recovery',
 'Exhaustion, burn-out, deep contemplation, stagnation, restlessness',
 '["rest", "contemplation", "recovery", "meditation"]'::jsonb,
 '["restlessness", "burn-out", "lack of progress"]'::jsonb,
 'air', 4),

(54, 'Five of Swords', 'swords', 'minor',
 'Conflict, disagreements, competition, defeat, winning at all costs, hostility',
 'Reconciliation, making amends, past resentment, winning graciously',
 '["conflict", "defeat", "hostility", "win at all costs"]'::jsonb,
 '["reconciliation", "making amends", "past grudges"]'::jsonb,
 'air', 5),

(55, 'Six of Swords', 'swords', 'minor',
 'Transition, change, rite of passage, releasing baggage, moving forward',
 'Personal transition, resistance to change, unfinished business',
 '["transition", "moving on", "change", "release"]'::jsonb,
 '["resistance to change", "unfinished business"]'::jsonb,
 'air', 6),

(56, 'Seven of Swords', 'swords', 'minor',
 'Betrayal, deception, getting away with something, stealth, strategy, cunning',
 'Imposter syndrome, self-deceit, keeping secrets, getting caught',
 '["deception", "betrayal", "strategy", "cunning"]'::jsonb,
 '["coming clean", "rethinking approach", "self-deceit"]'::jsonb,
 'air', 7),

(57, 'Eight of Swords', 'swords', 'minor',
 'Negative thoughts, self-imposed restriction, imprisonment, victim mentality',
 'Self-limiting beliefs, inner critic, releasing negative thoughts, freedom',
 '["restriction", "negative thoughts", "victim mentality"]'::jsonb,
 '["freedom", "releasing negativity", "new perspective"]'::jsonb,
 'air', 8),

(58, 'Nine of Swords', 'swords', 'minor',
 'Anxiety, worry, fear, depression, nightmares, guilt, stress, overwhelm',
 'Inner turmoil, deep-seated fears, shame, seeking help, light at the end',
 '["anxiety", "worry", "nightmares", "stress"]'::jsonb,
 '["hope", "reaching out", "facing fears"]'::jsonb,
 'air', 9),

(59, 'Ten of Swords', 'swords', 'minor',
 'Painful endings, deep wounds, betrayal, loss, crisis, hitting rock bottom',
 'Recovery, regeneration, resisting an inevitable end, learning from past',
 '["rock bottom", "painful ending", "betrayal", "crisis"]'::jsonb,
 '["recovery", "learning", "moving on"]'::jsonb,
 'air', 10),

(60, 'Page of Swords', 'swords', 'minor',
 'New ideas, curiosity, thirst for knowledge, new ways of communicating',
 'Self-expression, all talk and no action, haphazard action, using words to hurt',
 '["curiosity", "new ideas", "communication"]'::jsonb,
 '["all talk no action", "haphazard", "hurtful words"]'::jsonb,
 'air', 11),

(61, 'Knight of Swords', 'swords', 'minor',
 'Ambitious, action-oriented, driven to succeed, fast-thinking, opinionated',
 'Restless, unfocused, impulsive, burn-out, scattered energy',
 '["action", "ambition", "fast-thinking", "driven"]'::jsonb,
 '["impulsive", "unfocused", "restless"]'::jsonb,
 'air', 12),

(62, 'Queen of Swords', 'swords', 'minor',
 'Independent, unbiased judgment, clear boundaries, direct communication, honest',
 'Overly-emotional, easily influenced, bitty, cold, cruel, withdrawn',
 '["independent", "clear thinking", "direct", "honest"]'::jsonb,
 '["cold", "cruel", "bitter", "withdrawn"]'::jsonb,
 'air', 13),

(63, 'King of Swords', 'swords', 'minor',
 'Mental clarity, intellectual power, authority, truth, clear thinking',
 'Quiet power, inner truth, misuse of power, manipulation, tyranny',
 '["clarity", "authority", "truth", "intellectual"]'::jsonb,
 '["manipulation", "abuse of power", "coldness"]'::jsonb,
 'air', 14);

-- ==================================================
-- MINOR ARCANA - PENTACLES (Earth) - 64-77
-- ==================================================

INSERT INTO tarot_cards (card_number, name, suit, arcana_type, upright_meaning, reversed_meaning, upright_keywords, reversed_keywords, element, numerological_value) VALUES
(64, 'Ace of Pentacles', 'pentacles', 'minor',
 'Opportunity, prosperity, new venture, manifestation, abundance, financial opportunity',
 'Lost opportunity, missed chance, lack of planning, poor financial management',
 '["opportunity", "prosperity", "new venture", "manifestation"]'::jsonb,
 '["lost opportunity", "lack of planning", "poor management"]'::jsonb,
 'earth', 1),

(65, 'Two of Pentacles', 'pentacles', 'minor',
 'Multiple priorities, time management, prioritization, adaptability, juggling',
 'Over-committed, disorganization, reprioritization, overwhelmed',
 '["balance", "adaptability", "time management", "priorities"]'::jsonb,
 '["imbalance", "disorganization", "overwhelmed"]'::jsonb,
 'earth', 2),

(66, 'Three of Pentacles', 'pentacles', 'minor',
 'Teamwork, collaboration, learning, implementation, planning, competence',
 'Disharmony, misalignment, working alone, lack of teamwork, ego',
 '["teamwork", "collaboration", "skill", "competence"]'::jsonb,
 '["lack of teamwork", "disorganized", "ego"]'::jsonb,
 'earth', 3),

(67, 'Four of Pentacles', 'pentacles', 'minor',
 'Saving money, security, conservatism, scarcity, control, greed, possessiveness',
 'Over-spending, greed, self-protection, financial insecurity',
 '["security", "control", "conservatism", "saving"]'::jsonb,
 '["greed", "materialism", "financial insecurity"]'::jsonb,
 'earth', 4),

(68, 'Five of Pentacles', 'pentacles', 'minor',
 'Financial loss, poverty, lack mindset, isolation, worry, hardship, insecurity',
 'Recovery from financial loss, spiritual poverty, positive changes',
 '["hardship", "financial loss", "insecurity", "isolation"]'::jsonb,
 '["recovery", "positive change", "overcoming adversity"]'::jsonb,
 'earth', 5),

(69, 'Six of Pentacles', 'pentacles', 'minor',
 'Giving, receiving, sharing wealth, generosity, charity, fairness, community',
 'Self-care, unpaid debts, one-sided charity, strings attached',
 '["generosity", "charity", "sharing", "fairness"]'::jsonb,
 '["strings attached", "unpaid debts", "inequality"]'::jsonb,
 'earth', 6),

(70, 'Seven of Pentacles', 'pentacles', 'minor',
 'Long-term view, sustainable results, perseverance, investment, effort, patience',
 'Lack of long-term vision, limited success, impatience, lack of reward',
 '["patience", "perseverance", "investment", "long-term"]'::jsonb,
 '["impatience", "lack of reward", "limited success"]'::jsonb,
 'earth', 7),

(71, 'Eight of Pentacles', 'pentacles', 'minor',
 'Apprenticeship, skill development, quality, mastery, dedication, hard work',
 'Self-development, perfectionism, misdirected activity, lack of motivation',
 '["skill", "dedication", "mastery", "hard work"]'::jsonb,
 '["perfectionism", "lack of ambition", "misdirected effort"]'::jsonb,
 'earth', 8),

(72, 'Nine of Pentacles', 'pentacles', 'minor',
 'Abundance, luxury, self-sufficiency, financial independence, success, reward',
 'Self-worth, over-investment in work, hustling, financial setbacks',
 '["abundance", "luxury", "self-sufficiency", "success"]'::jsonb,
 '["over-investment", "financial setbacks", "work-life imbalance"]'::jsonb,
 'earth', 9),

(73, 'Ten of Pentacles', 'pentacles', 'minor',
 'Wealth, financial security, family, long-term success, contribution, legacy',
 'Financial failure, loneliness, loss, family disputes, bankruptcy',
 '["wealth", "family", "legacy", "long-term success"]'::jsonb,
 '["financial failure", "family disputes", "bankruptcy"]'::jsonb,
 'earth', 10),

(74, 'Page of Pentacles', 'pentacles', 'minor',
 'Manifestation, financial opportunity, skill development, new ideas, ambition',
 'Lack of progress, procrastination, learning from failure, perfectionism',
 '["opportunity", "manifestation", "ambition", "learning"]'::jsonb,
 '["procrastination", "lack of progress", "perfectionism"]'::jsonb,
 'earth', 11),

(75, 'Knight of Pentacles', 'pentacles', 'minor',
 'Hard work, productivity, routine, conservatism, efficiency, methodical',
 'Self-discipline, boredom, feeling stuck, perfectionism, workaholic',
 '["hard work", "efficiency", "routine", "methodical"]'::jsonb,
 '["workaholic", "feeling stuck", "perfectionism"]'::jsonb,
 'earth', 12),

(76, 'Queen of Pentacles', 'pentacles', 'minor',
 'Nurturing, practical, providing financially, down-to-earth, resourceful, trusted',
 'Self-care, work-home conflict, financial independence, jealousy',
 '["nurturing", "practical", "resourceful", "down-to-earth"]'::jsonb,
 '["work-home conflict", "jealousy", "smothering"]'::jsonb,
 'earth', 13),

(77, 'King of Pentacles', 'pentacles', 'minor',
 'Wealth, business, leadership, security, discipline, abundance, provider',
 'Financially inept, obstinate, flashy, poor judgment, corruption',
 '["wealth", "leadership", "abundance", "security"]'::jsonb,
 '["greed", "materialism", "corruption", "poor judgment"]'::jsonb,
 'earth', 14);

-- ==================================================
-- Verification Query
-- ==================================================
-- SELECT COUNT(*) FROM tarot_cards; -- Should return 78
-- SELECT arcana_type, COUNT(*) FROM tarot_cards GROUP BY arcana_type; -- Should show 22 major, 56 minor
-- SELECT suit, COUNT(*) FROM tarot_cards WHERE arcana_type = 'minor' GROUP BY suit; -- Should show 14 per suit
